Update to CAS and use SSL config

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,4 @@
-image: buildstream/buildstream-fedora:master-81-06ae434
+image: buildstream/buildstream-fedora:master-103-1016dcb4
 
 variables:
   # Store everything under the /builds directory. This is a separate Docker
@@ -6,7 +6,7 @@ variables:
   # directory.
   XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
   GET_SOURCES_ATTEMPTS: 3
-  BST_CACHE_SERVER_ADDRESS: 'artifacts.freedesktop.codethink.co.uk'
+  BST_CACHE_SERVER_ADDRESS: 'testcache.codethink.co.uk'
   BST_RELEASES_SERVER_ADDRESS: 'cache.sdk.freedesktop.org'
   BST_CACHE_SSH_USER: 'artifacts'
 
@@ -24,7 +24,7 @@ stages:
 
 before_script:
   - export PATH=~/.local/bin:${PATH}
-  - export BST_SHA='bc5a40e3dccbe1cb8066171fc2c0a4a5abeaa31e' #  1.1.3-177-gbc5a40e3
+  - export BST_SHA='7de8c1b85f8b0bf5b3d6c132432cc57796f47f7f' #  1.1.4
   - git clone https://gitlab.com/BuildStream/buildstream.git
   - git -C buildstream checkout $BST_SHA
   - pip3 install --user buildstream/
@@ -47,6 +47,18 @@ before_script:
         ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
     fi
 
+  # Create CAS directory for SSL keys
+  - mkdir -p /etc/ssl/CAS
+ 
+  # Private SSL keys/certs for psuhing to the CAS server
+  - |
+    if [ -z "$GITLAB_CAS_PUSH_CERT" ]; then
+       echo >&2 "Private CAS cert not found"
+    else
+       echo "$GITLAB_CAS_PUSH_CERT" > /etc/ssl/CAS/server.crt
+       echo "$GITLAB_CAS_PUSH_KEY" > /etc/ssl/CAS/server.key
+    fi
+
   # Use internal network only if we are using x86_64 runners from DigitalOcean
   - |
     if [ "${CI_RUNNER_DESCRIPTION}" == 'manager-runner-freedesktop' ]; then
@@ -65,11 +77,15 @@ before_script:
         echo "projects:" > ~/.config/buildstream.conf
         echo "  base-sdk-bootstrap:" >> ~/.config/buildstream.conf
         echo "    artifacts:" >> ~/.config/buildstream.conf
-        echo "      url: ssh://${BST_CACHE_SSH_USER}@${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      url: https://${BST_CACHE_SERVER_ADDRESS}:11002" >> ~/.config/buildstream.conf
+        echo "      client-key: /etc/ssl/CAS/server.key" >> ~/.config/buildstream.conf
+        echo "      client-cert: /etc/ssl/CAS/server.crt" >> ~/.config/buildstream.conf
         echo "      push: true" >> ~/.config/buildstream.conf
         echo "  base-sdk:" >> ~/.config/buildstream.conf
         echo "    artifacts:" >> ~/.config/buildstream.conf
-        echo "      url: ssh://${BST_CACHE_SSH_USER}@${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      url: https://${BST_CACHE_SERVER_ADDRESS}:11002" >> ~/.config/buildstream.conf
+        echo "      client-key: /etc/ssl/CAS/server.key" >> ~/.config/buildstream.conf
+        echo "      client-cert: /etc/ssl/CAS/server.crt" >> ~/.config/buildstream.conf
         echo "      push: true" >> ~/.config/buildstream.conf
     fi
 
@@ -136,7 +152,7 @@ build_i586:
     ARCH: i586
 
 build_aarch64:
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   <<: *build_definition
   tags:
     - aarch64
@@ -144,7 +160,7 @@ build_aarch64:
     ARCH: aarch64
 
 build_arm:
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   <<: *build_definition
   tags:
     - armhf
@@ -205,7 +221,7 @@ app_x86_64:
     ARCH: x86_64
 
 app_aarch64:
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   dependencies:
     - build_aarch64
   <<: *flatpak_definition
@@ -215,7 +231,7 @@ app_aarch64:
     ARCH: aarch64
 
 app_arm:
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   dependencies:
     - build_arm
   <<: *flatpak_definition
@@ -345,7 +361,7 @@ publish_i586:
 
 publish_aarch64:
   stage: publish_aarch64
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   <<: *flatpak_runtimes_publish
   tags:
     - aarch64
@@ -354,7 +370,7 @@ publish_aarch64:
 
 publish_arm:
   stage: publish_arm
-  image: buildstream/buildstream-fedora:aarch64-master-81-06ae434
+  image: buildstream/buildstream-fedora:aarch64-master-103-709b9bca
   <<: *flatpak_runtimes_publish
   tags:
     - armhf
